---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
non-functional:
  - Веб-сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен иметь мобильную версию #Ключевой возможностью магазина будет адаптивная верстка, чтобы он был удобным на мобильных устройствах
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах
implicit:
  - асинхронная загрузка
  - оптимизация изображений
  - включение кеширования файлов
  - минификация файлов HTML
  - минификация файлов CSS
  - минификация файлов JavaScript
  - протокол HTTPS
  - функция поиска по ключевому слову
  - функция поиска по категории товара
  - описание товара должно включать ключевые слова
  - товар должен быть соотнесен по категориям товаров
  - фильтрация товаров по рейтингу
  - фильтрация товаров по цене
  - фильтрация по скидке на цену товара
  - синхронизация актуальных цен на товары в веб-версии и мобильной версии сайта
  - синхронизация актуального списка товаров в веб-версии и мобильной версии сайта
  - синхронизация корзины в веб-версии и мобильной версии сайта
  - тестирование совместимости веб-версии ПО на браузере Google Chrome v.114
  - тестирование совместимости веб-версии ПО на браузере Google Chrome v.115
  - тестирование совместимости веб-версии ПО на браузере Safari v.16.5
  - тестирование совместимости веб-версии ПО на браузере Firefox v.115
  - тестирование совместимости мобильной версии ПО на браузере Chrome for Android v.115
  - тестирование совместимости мобильной версии ПО на браузере Safari on iOS v.16.5
  - тестирование совместимости мобильной версии ПО на браузере Firefox for Android v.115
  - система должна выдерживать нагрузку в 1000 пользователей
  - платежная система должна выдерживать 500 запросов в секунду
  - в каталоге на каждой карточке товара есть информация о названии, описание, рейтинге, цене со скидкой, полной цене
  - в каталоге на каждой карточке товара есть кнопка "добавить в корзину"
  - на всех страницах магазина есть кнопка "корзина"
  - на странице "корзина" есть возможность просмотреть карточки добавленных товаров
  - на странице "корзина" есть возможность изменить количество добавленных товаров
  - на странице "корзина" есть возможность удалить добавленные товары
  - на странице "корзина" есть кнопка "каталог"
  - на странице "корзина" есть кнопка "оплата"
  - на странице "оплата" есть возможность оплатить товар через платежную систему
  - на странице "оплата" есть кнопка "отмена" с переход обратно в "корзину"
  - тестирование адаптивности веб-версии ПО на браузере Firefox v.115
