---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
  - Пользователь может добавить товар в корзину и продолжить выбирать товары в каталоге
non-functional:
  - Веб-сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен иметь мобильную версию
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах
implicit:
  - Адаптивная верстка #Ключевой возможностью магазина будет адаптивная верстка, чтобы он был удобным на мобильных устройствах
  - SPA-приложение #без перезагрузки страницы, постраничный вывод
  - На странице товара выводятся фото, название, рейтинг, цена со скидкой и без
  - На странице каталога выводятся фото, название, рейтинг, цена со скидкой и без
  - На странице корзины пользователь может удалить товар из корзины
  - На странице корзины пользователь может продолжить выбирать товары в каталоге
  - На странице корзины пользователь может оформить заказ с переходом на страницу оплаты
  - функция поиска по ключевому слову в названии товара
  - фильтр по категориям товаров
  - фильтр диапазона цен на товары
  - система должна выдерживать нагрузку в 1000 пользователей
  - платежная система должна выдерживать 500 запросов в секунду
