---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
non-functional:
  - Веб-сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен иметь мобильную версию
implicit:
  - асинхронная загрузка
  - оптимизация изображений
  - включение кеширования файлов
  - минификация файлов HTML
  - минификация файлов CSS
  - минификация файлов JavaScript
  - протокол HTTPS
  - функция поиска по ключевому слову
  - функция поиска по категории товара
  - описание товара должно включать ключевые слова
  - товар должен быть соотнесен по категориям товаров
  - фильтрация товаров по рейтингу
  - фильтрация товаров по цене
  - фильтрация по скидке на цену товара
  - синхронизация актуальных цен на товары в веб-версии и мобильной версии сайта
  - синхронизация актуального списка товаров в веб-версии и мобильной версии сайта
  - синхронизация актуальных цен на товары в веб-версии и мобильной версии сайта
